services:
#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:24.0.4
#    environment:
#      KC_HOSTNAME: localhost
#      KC_HOSTNAME_PORT: 8081
#      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak?characterEncoding=UTF-8
#      KC_DB_USERNAME: admin
#      KC_DB_PASSWORD: admin
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HEALTH_ENABLED: "true"
#      KC_LOG_LEVEL: info
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8081/health/ready" ]
#      interval: 15s
#      timeout: 2s
#      retries: 15
#    depends_on:
#      - keycloak_postgres
#    command:
#      - start-dev
#      - --import-realm
#    volumes:
#      - ./realm-import.json:/opt/keycloak/data/import/realm-import.json
#    ports:
#      - 8081:8080
#    networks:
#      - chat-app

  backend_postgres:
    container_name: backend_postgres
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: chat-app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "15436:5432"
    networks:
      - chat-app

#  keycloak_postgres:
#    container_name: keycloak_postgres
#    image: postgis/postgis:16-3.4
#    environment:
#      POSTGRES_DB: keycloak
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#    networks:
#      - chat-app

networks:
  chat-app:
    external: false